model_name: "tabura"

target_phrase:
  - "tah boo rah"

custom_negative_phrases:
  - "taboo"
  - "abra"
  - "toolbar"
  - "tumblr"
  - "ta da"

n_samples: 2000
n_samples_val: 500
tts_batch_size: 25
augmentation_batch_size: 16
augmentation_rounds: 3
total_length: 32000

piper_sample_generator_path: "data/piper-sample-generator"
output_dir: "output"

rir_paths: []

background_paths:
  - "data/audioset_16k"
  - "data/fma_small"

background_paths_duplication_rate:
  - 1
  - 1

false_positive_validation_data_path: "data/validation_set_features.npy"

feature_data_files:
  "ACAV100M_sample": "data/openwakeword_features_ACAV100M_2000_hrs_16bit.npy"

batch_n_per_class:
  "ACAV100M_sample": 1024
  "adversarial_negative": 50
  "positive": 50

model_type: "dnn"
layer_size: 32

steps: 50000
max_negative_weight: 1500
target_false_positives_per_hour: 0.2
