model_name: "sloppy"

target_phrase:
  - "slop ee"

custom_negative_phrases:
  - "copy"
  - "happy"
  - "poppy"
  - "soapy"
  - "sleepy"
  - "slowly"
  - "sorry"
  - "soppy"
  - "stocky"
  - "rocky"

n_samples: 5000
n_samples_val: 1000
tts_batch_size: 8
augmentation_batch_size: 8
augmentation_rounds: 5
total_length: 32000

piper_sample_generator_path: "data/piper-sample-generator"
output_dir: "output"

rir_paths: []

background_paths:
  - "data/audioset_16k"
  - "data/fma_small"

background_paths_duplication_rate:
  - 1
  - 1

false_positive_validation_data_path: "data/validation_set_features.npy"

feature_data_files:
  "ACAV100M_sample": "data/openwakeword_features_ACAV100M_2000_hrs_16bit.npy"

batch_n_per_class:
  "ACAV100M_sample": 1024
  "adversarial_negative": 50
  "positive": 50

model_type: "dnn"
layer_size: 64

steps: 100000
max_negative_weight: 1000
target_false_positives_per_hour: 1.0
