package surface

import "strings"

func ProtocolBodyMarkdown() string {
	var b strings.Builder
	b.WriteString("## Tabula Codex Protocol\n\n")
	b.WriteString("Use this protocol for Tabula interactive sessions in this project.\n\n")
	b.WriteString("1. Read extra instructions from `.tabula/prompt-injection.txt` and apply them.\n")
	b.WriteString("2. Keep generated render/output artifacts under `.tabula/artifacts`; keep editable source files in the project workspace (not under `.tabula/artifacts`).\n")
	b.WriteString("3. Use MCP server `tabula` for all canvas operations; do not rely on filesystem event logs.\n")
	b.WriteString("4. MCP tools: ")
	b.WriteString(MCPToolNamesCSV())
	b.WriteString(".\n")
	b.WriteString("5. Keep interaction chat-canvas-first in the web UI; do not depend on a terminal REPL.\n")
	b.WriteString("6. Keep `.tabula/artifacts/` gitignored; do not commit files from it unless explicitly requested.\n")
	return b.String()
}

func ProtocolBlockMarkdown() string {
	var b strings.Builder
	b.WriteString(ProtocolBlockBeginMarker)
	b.WriteString("\n")
	b.WriteString(ProtocolBodyMarkdown())
	b.WriteString("\n")
	b.WriteString(ProtocolBlockEndMarker)
	b.WriteString("\n")
	return b.String()
}

func DefaultAgentsMarkdown() string {
	return "# AGENTS\n\n" + ProtocolBlockMarkdown()
}

func InterfacesMarkdown() string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./cmd/surfacegen`. DO NOT EDIT. -->\n\n")
	b.WriteString("# Interfaces\n\n")
	b.WriteString("This document summarizes externally relevant interfaces in the current release.\n\n")

	b.WriteString("## MCP HTTP Daemon\n\n")
	b.WriteString("Routes in `internal/serve/app.go`:\n")
	for _, route := range MCPDaemonRoutes {
		b.WriteString("- `")
		b.WriteString(route)
		b.WriteString("`\n")
	}
	b.WriteString("\n")

	b.WriteString("## Web Runtime HTTP APIs\n\n")
	for _, section := range WebRouteSections {
		b.WriteString(section.Title)
		b.WriteString(":\n")
		for _, route := range section.Routes {
			b.WriteString("- `")
			b.WriteString(route)
			b.WriteString("`\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## MCP Tool Surface\n\n")
	b.WriteString("Defined in `internal/surface/definitions.go` and used by `internal/mcp/server.go`:\n")
	for _, tool := range MCPTools {
		b.WriteString("- `")
		b.WriteString(tool.Name)
		b.WriteString("`\n")
	}
	b.WriteString("\n")

	b.WriteString("## Reply Intent Contract\n\n")
	b.WriteString("`POST /api/mail/draft-intent` returns classification metadata including:\n")
	b.WriteString("- `intent` (`prompt` or `dictation`)\n")
	b.WriteString("- `reason`\n")
	b.WriteString("- `fallback_applied`\n")
	b.WriteString("- `fallback_policy`\n\n")
	b.WriteString("`POST /api/mail/draft-reply` returns generated or prepared draft text for explicit user review.\n\n")
	b.WriteString("## Stability Statement\n\n")
	b.WriteString("The current release is pre-stable; interfaces may evolve. Breaking changes are documented in release notes.\n")
	return b.String()
}
