package surface

import "strings"

func InterfacesMarkdown() string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by `go run ./cmd/surfacegen`. DO NOT EDIT. -->\n\n")
	b.WriteString("> **Legal notice:** Tabura is provided \"as is\" and \"as available\" without warranties, and to the maximum extent permitted by applicable law the authors/contributors accept no liability for damages, data loss, or misuse. You are solely responsible for backups, verification, and safe operation. See [`DISCLAIMER.md`](../DISCLAIMER.md).\n\n")
	b.WriteString("# Interfaces\n\n")
	b.WriteString("This document summarizes externally relevant interfaces in the current release.\n\n")

	b.WriteString("## MCP HTTP Daemon\n\n")
	b.WriteString("Routes in `internal/serve/app.go`:\n")
	for _, route := range MCPDaemonRoutes {
		b.WriteString("- `")
		b.WriteString(route)
		b.WriteString("`\n")
	}
	b.WriteString("\n")

	b.WriteString("## Web Runtime HTTP APIs\n\n")
	for _, section := range WebRouteSections {
		b.WriteString(section.Title)
		b.WriteString(":\n")
		for _, route := range section.Routes {
			b.WriteString("- `")
			b.WriteString(route)
			b.WriteString("`\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## MCP Tool Surface\n\n")
	b.WriteString("Defined in `internal/surface/definitions.go` and used by `internal/mcp/server.go`:\n")
	for _, tool := range MCPTools {
		b.WriteString("- `")
		b.WriteString(tool.Name)
		b.WriteString("`\n")
	}
	b.WriteString("\n")
	b.WriteString("## Stability Statement\n\n")
	b.WriteString("The current release is pre-stable; interfaces may evolve. Breaking changes are documented in release notes.\n")
	return b.String()
}
